Document: quickpad
Title: Debian quickpad Manual
Author: <insert document author here>
Abstract: This manual describes what quickpad is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/quickpad/quickpad.sgml.gz

Format: postscript
Files: /usr/share/doc/quickpad/quickpad.ps.gz

Format: text
Files: /usr/share/doc/quickpad/quickpad.text.gz

Format: HTML
Index: /usr/share/doc/quickpad/html/index.html
Files: /usr/share/doc/quickpad/html/*.html
